<?php

namespace app\admin\controller;

use think\Controller;
use think\Db;
use think\Request;

class HotelItem extends Controller
{
    public $code;
    public $validate;


//对一些属性进行初始化
    public function __construct(Request $request = null)
    {
        parent::__construct($request);
        $this->code=config('code');
        $this->validate=validate("HotelItem");
    }

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        checkToken();
    }


    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        $data=$this->request->get();
        //分页
        if(isset($data['page']) && !empty($data['page'])){
            $page=$data['page'];
        }else{
            $page=1;
        }

        if(isset($data['limit']) && !empty($data['limit'])){
            $limit=$data['limit'];
        }else{
            $limit=5;
        }
        //处理搜索条件
        $where=[];
        if(isset($data['scity']) && !empty($data['scity'])){
            $where['scity']=$data['scity'];
        }
        if(isset($data['sname']) && !empty($data['sname'])){
            $where['sname']=['like','%'.$data['sname'].'%'];
        }
        $result=Db::table('hotel_item')->field('hid,hname,hprice,hscore,htype,hprovince,hcity,harea,haddress')->where($where)->paginate($limit,false,['page'=>$page]);
        $hotelItem=$result->items();
        $total=$result->total();
        if($hotelItem && $total){
            return json([
                'code'=>$this->code['success'],
                'msg'=>"数据查询成功",
                'data'=>$hotelItem,
                'total'=>$total,
            ]);
        }

    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        $data=$this->request->post();
//判断酒店是否已存在
        $hname=$data['hname'];
        $isExist=Db::table('hotel_item')->where('hname',$hname)->count();
        if($isExist){
            return json([
                'code'=>$this->code['fail'],
                'msg'=>"该酒店已经注册过了！"
            ]);
        }
        $result=Db::table('hotel_item')->insert($data);
        if($result){
            return json([
                'code'=>$this->code['success'],
                'msg'=>"数据插入成功！"
            ]);
        }else{
            return json([
                'code'=>$this->code['fail'],
                'msg'=>"数据插入成功！"
            ]);
        }

    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id)
    {
        //
        return "read";
    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
